# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField()),
                ('date_exp', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('rating', models.IntegerField()),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('access', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
