# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180702_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_exp',
            field=models.DateField(),
        ),
    ]
